
const introduction = "## Introduction"
const header = """

<!-- This file is generated by `.github/workflows/readme.yml`; do not edit directly. -->

<p align="center"><img width="200px" src="docs/src/assets/logo.svg"/></p>

<div align="center">

[![Documentation stable](https://img.shields.io/badge/Documentation-stable-blue.svg)](https://jakobjpeters.github.io/PAndQ.jl/stable/)
[![Documentation dev](https://img.shields.io/badge/Documentation-dev-blue.svg)](https://jakobjpeters.github.io/PAndQ.jl/dev/)

[![Documentation](https://github.com/jakobjpeters/PAndQ.jl/workflows/Documentation/badge.svg)](https://github.com/jakobjpeters/PAndQ.jl/actions/workflows/documentation.yml)
[![Continuous Integration](https://github.com/jakobjpeters/PAndQ.jl/workflows/Continuous%20Integration/badge.svg)](https://github.com/jakobjpeters/PAndQ.jl/actions/workflows/continuous_integration.yml)

[![Codecov](https://codecov.io/gh/jakobjpeters/PAndQ.jl/branch/main/graph/badge.svg?token=XFWU66WSD7)](https://codecov.io/gh/jakobjpeters/PAndQ.jl)
[![Dependents](https://docs.juliahub.com/PAndQ/deps.svg)](https://juliahub.com/ui/Packages/PAndQ/h95uE/0.1.0?page=2)

</div>

# PAndQ.jl

"""

write("README.md", header * introduction * replace(last(split(read(
    "docs/src/index.md", String), introduction)), "jldoctest" => "julia"))
